# Generated by Django 6.1.1 on 2026-09-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(height_field='height', upload_to='paintings/', width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('medium', models.CharField(blank=True, help_text='Example: Oil on canvas', max_length=120)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, help_text='Example: 60 x 80 cm', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('not_for_sale', 'Not for sale')], default='available', max_length=20)),
                ('price', models.CharField(blank=True, help_text='Free text. Example: ₦250,000 or $400', max_length=60)),
                ('payment_link', models.URLField(blank=True, help_text='Optional Paystack, Flutterwave or PayPal link')),
                ('tint', models.CharField(default='#1b2320', editable=False, max_length=7)),
                ('position', models.PositiveIntegerField(default=0, help_text='Lower numbers hang first')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', '-created'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Artist Name', max_length=80)),
                ('tagline', models.CharField(blank=True, default='Paintings, hung slowly', max_length=140)),
                ('bio', models.TextField(blank=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Country code, digits only. Example: 2348012345678', max_length=20, verbose_name='WhatsApp number')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'site profile',
                'verbose_name_plural': 'site profile',
            },
        ),
    ]
