# Generated by Django 6.1.1 on 2026-09-28 11:30

import django.db.models.deletion
import gallery.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number only, e.g. 250000. Leave empty to take enquiries only.', max_digits=12, null=True, verbose_name='Price in naira (for online checkout)'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('requested', 'Requested (artist will contact buyer)'), ('pending', 'Awaiting payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField(verbose_name='Delivery address')),
                ('reference', models.CharField(default=gallery.models.new_reference, editable=False, max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='gallery.painting')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
