# Generated by Django 6.1.1 on 2026-09-28 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_painting_price_amount_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(help_text='What would you like painted?')),
                ('budget', models.CharField(blank=True, help_text='Optional budget range', max_length=60)),
                ('status', models.CharField(choices=[('new', 'New'), ('discussing', 'In discussion'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='new', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CommissionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commissions/%Y/%m/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='gallery.commissionrequest')),
            ],
        ),
    ]
